name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  rxdart: ^0.26.0
  google_atlas:
    path: ../packages/google_atlas

flutter:
  uses-material-design: true
  assets:
    - assets/
